Fix factory resolver API
eclipse-che/che-server pull request #505
Opened 2023-04-19 15:16 UTC by olexii4

### What does this PR do?
Fix factory resolver API.

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

### How to test this PR?

1. Try to use the swagger and resolve factory with https://gist.githubusercontent.com/olexii4/fc3b757806e660dee0fbe1bc131df3d1/raw/c887e6920f43825755e1569ea5d3ec93ffd9a538/empty.yaml
```{ "url": "https://gist.githubusercontent.com/olexii4/fc3b757806e660dee0fbe1bc131df3d1/raw/c887e6920f43825755e1569ea5d3ec93ffd9a538/empty.yaml" }```
 ![Знімок екрана 2023-04-19 о 18 09 28](https://user-images.githubusercontent.com/6310786/233120774-78b45f8c-8dca-423f-82fc-1efe49af2aaf.png)
2. Turn on schema validation and try again.
![Знімок екрана 2023-04-19 о 18 09 28](https://user-images.githubusercontent.com/6310786/233121573-ee3e9fc2-d4dc-4ed8-bac7-d65a561e1f82.png)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2023-04-19 15:26 UTC, ibuziuk commented on wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
> +    if (validate.equals("true")) {
```suggestion
    if ("true".equals(validate)) {
```

2023-04-19 15:28 UTC, ibuziuk approved these changes

2023-04-19 17:42 UTC, olexii4 commented
/retest

2023-04-20 07:58 UTC, vinokurig requested changes
The request fails even before the check here:
https://github.com/eclipse-che/che-server/blob/main/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileParser.java#L124
I don't see any problems with the boolean serialisation.

2023-04-20 13:36 UTC, olexii4 commented
@vinokurig Thanks. I have fixed it.

2023-04-20 13:54 UTC, vinokurig commented
@olexii4 I am not sure that removing the validator at all is a right choice. How about fixing the validator itself?

2023-04-20 14:15 UTC, closed without merging